version: '3'

services:
    koto:
        build:
            context: .
            target: base
        tty: true
        command: yarn docker:start
        env_file: ./.env
        ports:
            - '$EXPOSED_API_PORT:3000'
            - '$EXPOSED_DEBUGGING_PORT:9229'
        volumes:
            - ./:/opt/app
        depends_on:
            - db
    db:
        image: postgres:12.2
        environment:
            - 'POSTGRES_USER=$DATABASE_USER'
            - 'POSTGRES_PASSWORD=$DATABASE_PASSWORD'
            - 'POSTGRES_DB=$DATABASE_NAME'
        ports:
            - '$EXPOSED_DATABASE_PORT:5432'
